<a href="https://colab.research.google.com/github/aniruddhamodak/Python-Notes-For-Data-Science/blob/master/10_Pandas_for_data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

# Pandas is an important Python library for data manipulation, wrangling, 
# and analysis. It functions as an intuitive and easy-to-use set of tools 
# for performing operations on any kind of data.

Data Structures of Pandas
-------------------------
All the data representation in pandas is done using two primary data structures:
• Series
• Dataframes

Series
1> Series in pandas is a one-dimensional ndarray with an axis label. It means that in functionality, it is almost similar to a simple array. The values in a series will have an index that needs to be hashable. 
2> This requirement is needed when we perform manipulation and summarization on data contained in a series data structure. Series objects can be used to represent time series data also. In this case, the index is a datetime object.

Dataframe
1> Dataframe is the most important and useful data structure, which is used for almost all kind of data representation and manipulation in pandas. Unlike numpy arrays (in general) a dataframe can contain heterogeneous data. 
2> Typically tabular data is represented using dataframes, which is analogous to an Excel sheet or a SQL table. This is extremely useful in representing raw datasets as well as processed feature sets in Machine Learning and Data Science. 
3> All the operations can be performed along the axes, rows, and
columns, in a dataframe.

In [0]:
#   Tip :
# ---------
import pandas
# [1]
pandas.__version__

'0.25.1'

In [0]:
# Just as we generally import NumPy under the alias np, 
# we will import Pandas under the alias pd:

# [2]
import pandas as pd

In [0]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [0]:
# Example of series data type 

population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Constructing Series objects
---------------------------
We’ve already seen ways of constructing a Pandas Series from scratch; all of
them are some version of the following:

>>> pd.Series(data, index=index)

where index is an optional argument, and data can be one of many entities.

For example, data can be a list or NumPy array, in which case index defaults to an integer sequence:

In [0]:
# [5]
pd.Series( [2,4,6] ,index=['A', 'B','C'] )

A    2
B    4
C    6
dtype: int64

In [0]:
# [6]
pd.Series( 5, index=['A', 'B','C']  )

A    5
B    5
C    5
dtype: int64

In [0]:
# data can be a dictionary, in which index defaults 
# to the sorted dictionary keys:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [0]:
# In each case, the index can be explicitly set 
# if a different result is preferred:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

Constructing Dataframes
-----------------------
The next fundamental structure in Pandas is the DataFrame. 
Like the Series object, the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.

A Pandas DataFrame can be constructed in a variety of ways. 
Here we’ll give several examples.

> From a single Series object. 
A DataFrame is a collection of Series objects, and a single column
DataFrame can be constructed from a single Series:

In [0]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
pd.DataFrame(population,  columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

From a list of dicts. Any list of dictionaries can be made into a DataFrame. We’ll use a simple list comprehension to create some data
--

In [0]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(data)
df=pd.DataFrame(data,index=['X','Y','Z'])
#try this   df=pd.DataFrame(data,index=['X','Y','Z'])
print(df)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]
   a  b
X  0  0
Y  1  2
Z  2  4


In [0]:
df.columns=['Indranil','Nitin']
df

Indranil  Nitin
X         0      0
Y         1      2
Z         2      4

In [0]:
# Even if some keys in the dictionary are missing, 
# Pandas will fill them in with NaN (i.e., “not a number”) values:

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

Making a data frame from a two-dimensional NumPy array. 
-------------------------------------------------------

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each:

In [0]:
import numpy as np
# [14]
pd.DataFrame(np.random.randn(3,2), index=['a','b','c'] , columns=['foo','bar']  )


foo       bar
a -1.477521  0.667910
b  0.179146 -1.342865
c  1.622788  0.190100

# Note on : Indexers: loc and iloc

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [0]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [0]:
# explicit index when indexing
data[1]

'a'

In [0]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.

First, the loc attribute allows indexing and slicing that always references the explicit index:

In [0]:
data

1    a
3    b
5    c
dtype: object

In [0]:
# [19]
data.loc[1]

'a'

In [0]:
# [20]
data.loc[1:3]

1    a
3    b
dtype: object

The iloc attribute allows indexing and slicing that always 
references the implicit Python-style index:

In [0]:
data

1    a
3    b
5    c
dtype: object

In [0]:
# [22]
data.iloc[1]

'b'

In [0]:
# [23]
data.iloc[1:3]

3    b
5    c
dtype: object

# Data Retrieval

Data Retrieval
--------------
Pandas provides numerous ways to retrieve and read in data. We can convert data from CSV files, databases, flat files, and so on into dataframes. We can also convert a list of dictionaries (Python dict) into a dataframe.

We will cover three of the most important data sources:
• List of dictionaries
• CSV files
• Databases

In [0]:
# List of Dictionaries to Dataframe

import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)  

# Two important things to note here: 
# first,  the keys of dictionary are picked up as the column names 
# in the dataframe 
# secondly, it picks up the default index of normal arrays.

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [0]:
# CSV Files to Dataframe  -> read student_records.csv file

data=pd.read_csv('./datasets_n_images/datasets_module_1/student_records.csv')
data.head()

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No

In [0]:
# [26]
data.tail()

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

# Databases to Dataframe

import cx_Oracle

server = 'xxxxxxxx' # Address of the database server
user = 'xxxxxx'     # the username for the database server
password = 'xxxxx'  # Password for the above user


conn = cx_Oracle.connect(server=server, user=user, password=password)

query = "select * from some_table"

df = pd.read_sql(query, conn)

# Data Access

Data Access
------------
The most important part after reading in our data is that of accessing that data using the data structure’s access mechanisms. 

Accessing data in the pandas dataframe and series objects is very much similar to the access mechanism that exist for Python lists or numpy arrays.

In [0]:
# [27]
data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [0]:
# [28]
series_es = data.ProjectScore
series_es

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: ProjectScore, dtype: int64

In [0]:
series_es[1:7]

1    51
2    17
3    71
4    30
5    79
6    59
Name: ProjectScore, dtype: int64

In [0]:
# [29]
series_es[1:7:2]

1    51
3    71
5    79
Name: ProjectScore, dtype: int64

In [0]:
series_es[:5] 

0    85
1    51
2    17
3    71
4    30
Name: ProjectScore, dtype: int64

In [0]:
series_es

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: ProjectScore, dtype: int64

In [0]:
series_es[:-5] 

0    85
1    51
2    17
Name: ProjectScore, dtype: int64

In [0]:
data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [0]:
# [32]
data.iloc[ :5, :2 ]

Name OverallGrade
0   Henry            A
1    John            C
2   David            F
3  Holmes            B
4  Marvin            E

In [0]:
# Another access mechanism is Boolean based access to the dataframe rows 
# or columns.  
# Let’s consider the following example in which we want to select students 
# that have ResearchScore of more than 60 and their name starts with 'H':

import warnings; warnings.simplefilter('ignore')  # to suppress warnings

#data[data['ResearchScore'] > 60] [data['Name'].startswith('h')] #AttributeError: 'Series' object has no attribute 'startswith'

data[data['ResearchScore'] > 60] [data['Name'].str.startswith('H')]

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
3  Holmes            B        Y             75            71        No

When we select data based on some condition, we always get the part of dataframe that satisfies the condition supplied. 

Sometimes we want to test a condition against a dataframe but want to preserve the shape of the dataframe. In these cases, we can use the where function.

In [0]:
data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [0]:
data[data['ResearchScore'] > 79]

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Henry            A        Y             90            85       Yes
1   John            C        N             85            51       Yes
5  Simon            A        Y             92            79       Yes

In [0]:
_greater_80  = data.where(data.ResearchScore > 79)
_greater_80

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Henry            A        Y           90.0          85.0       Yes
1   John            C        N           85.0          51.0       Yes
2    NaN          NaN      NaN            NaN           NaN       NaN
3    NaN          NaN      NaN            NaN           NaN       NaN
4    NaN          NaN      NaN            NaN           NaN       NaN
5  Simon            A        Y           92.0          79.0       Yes
6    NaN          NaN      NaN            NaN           NaN       NaN
7    NaN          NaN      NaN            NaN           NaN       NaN

# Data Operations

Data Operations
---------------
The pandas dataframe will be our data structure of choice for most data
processing and wrangling operations. 

Hence lets look at some most common data Operations.

In [0]:
# creating a dataframe from NumPy array. Also adding column names.
df = pd.DataFrame(np.random.randn(8,3),columns=['A', 'B', 'C'])
df

A         B         C
0  1.284617  0.287388  0.182762
1 -0.655718 -1.044126  1.095444
2  1.255730 -1.822431 -0.394681
3 -0.462172 -0.516358  0.854182
4  0.488400 -0.288360  0.716196
5 -0.827228  0.017311 -0.013777
6  0.441104  2.067603 -0.796823
7 -1.082415 -0.249487  0.630423

In [0]:
# we can extract all values from the data frame and get a np array. 
nparray = df.values
print(type(nparray))
print(nparray)

<class 'numpy.ndarray'>
[[-0.92155889  0.23325035  0.08320728]
 [-0.44043599 -0.84780274 -1.23021559]
 [-0.40332846  0.26030774  0.6726008 ]
 [-0.56453507  1.0922182   0.00408954]
 [-1.75911716 -0.70283644  0.10297385]
 [-0.83939998  0.48219343  0.64833252]
 [ 0.62382478  0.09636796 -0.26564996]
 [-0.26392261 -1.64738304  0.32003693]]


Missing Data and the fillna Function
------------------------------------
In real-world datasets, the data is seldom clean and polished. 

We usually will have a lot of issues with data quality (missing values, wrong values and so on). 

One of the most common data quality issues is that of missing data. 

Pandas provides us with a convenient function that allows us to handle the missing values of a dataframe.

In [0]:
df

A         B         C
0  1.284617  0.287388  0.182762
1 -0.655718 -1.044126  1.095444
2  1.255730 -1.822431 -0.394681
3 -0.462172 -0.516358  0.854182
4  0.488400 -0.288360  0.716196
5 -0.827228  0.017311 -0.013777
6  0.441104  2.067603 -0.796823
7 -1.082415 -0.249487  0.630423

In [0]:
# make the element 4,2 as NaN
from numpy import nan
# [38]
df.iloc[4,2]=nan
df.iloc[3,1]=nan
df.iloc[1,0]=nan
print(df)

          A         B         C
0  1.284617  0.287388  0.182762
1       NaN -1.044126  1.095444
2  1.255730 -1.822431 -0.394681
3 -0.462172       NaN  0.854182
4  0.488400 -0.288360       NaN
5 -0.827228  0.017311 -0.013777
6  0.441104  2.067603 -0.796823
7 -1.082415 -0.249487  0.630423


In [0]:
# [39]
df.fillna(0)

A         B         C
0  1.284617  0.287388  0.182762
1  0.000000 -1.044126  1.095444
2  1.255730 -1.822431 -0.394681
3 -0.462172  0.000000  0.854182
4  0.488400 -0.288360  0.000000
5 -0.827228  0.017311 -0.013777
6  0.441104  2.067603 -0.796823
7 -1.082415 -0.249487  0.630423

In [0]:
import numpy as np
import pandas as pd

vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [0]:
1 + np.nan  

nan

NaN and None in Pandas
----------------------
NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate.

NaN can be used as a numerical value on mathematical operations, while None cannot (or at least shouldn't).

NaN is a numeric value, as defined in IEEE 754 floating-point standard. None is an internal Python type (NoneType) and would be more like "inexistent" or "empty" than "numerically invalid" in this context.

The main "symptom" of that is that, if you perform, say, an average or a sum on an array containing NaN, even a single one, you get NaN as a result...

In the other hand, you cannot perform mathematical operations using None as operand.

So, depending on the case, you could use None as a way to tell your algorithm not to consider invalid or inexistent values on computations. That would mean the algorithm should test each value to see if it is None.

In [0]:
# [42]
pd.Series( [1, np.nan, 2, None] )

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

For types that don’t have an available sentinel value, Pandas automatically type-casts when NA values are present. For example, if we set a value in an integer array to np.nan, it will automatically be upcast to a floating-point type to accommodate the NA:

In [0]:
x = pd.Series(range(2), dtype=int)
print(x)


print("--------------")
x[0] = None
print(x)
#Note: nan dataype is float64

0    0
1    1
dtype: int32
--------------
0    NaN
1    1.0
dtype: float64


# Descriptive Statistics Functions

Descriptive Statistics Functions
--------------------------------
A general practice of dealing with datasets is to know as much about them as possible. 

Descriptive statistics of a dataframe give data scientists a comprehensive look into important information about any attributes and features in the dataset. 

Pandas packs a bunch of functions, which facilitate easy access to these statistics.

In [0]:
data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [0]:
# [43]
columns_numeric = ['ResearchScore','ProjectScore']
data[columns_numeric].mean()

ResearchScore    63.375
ProjectScore     53.125
dtype: float64

In [0]:
data[columns_numeric].sum()

ResearchScore    507
ProjectScore     425
dtype: int64

In [0]:
data[columns_numeric].count() 

ResearchScore    8
ProjectScore     8
dtype: int64

In [0]:
data[columns_numeric].median()

ResearchScore    75.0
ProjectScore     55.0
dtype: float64

In [0]:
data[columns_numeric].quantile(0.8)  

ResearchScore    88.0
ProjectScore     75.8
Name: 0.8, dtype: float64

All these basic stats operations were applied to each of the columns, the default behavior. ( i.e axis = 0 )

We can also get all these statistics for each row by using a different axis.
 ( specify axis = 1 )

In [0]:
data[columns_numeric]

ResearchScore  ProjectScore
0             90            85
1             85            51
2             10            17
3             75            71
4             20            30
5             92            79
6             60            59
7             75            33

In [0]:
data[columns_numeric].sum(axis = 1)  # adds ResearchScore and Project Score

0    175
1    136
2     27
3    146
4     50
5    171
6    119
7    108
dtype: int64

In [0]:
data[columns_numeric].describe()

# Concatenating Dataframes

Concatenating Using the concat Method
-------------------------------------
Most Data Science projects will have data from more than one data source. 

These data sources will mostly have data that’s related in some way to each other and data analysis will require them to be concatenated or joined. 

Pandas provides a rich set of functions that allow us to merge different
data sources.

In [0]:
## Let’s look at some examples to understand how the concat method works.

data1 = data.sample(3)  # random subset of main data frame
data2 = data.sample(3)
print(data1,"\n")
print(data2)

### Concatanating data frames
data_combine = pd.concat([data1,data2])
data_combine

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
7   Trent            C        Y             75            33        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No 

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
3  Holmes            B        Y             75            71        No
2   David            F        N             10            17        No
1    John            C        N             85            51       Yes


Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
7   Trent            C        Y             75            33        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
3  Holmes            B        Y             75            71        No
2   David            F        N             10            17        No
1    John            C        N             85            51       Yes

In [0]:
# Another common scenario of concatenating is when we have information 
# about the columns of same dataframe split across different dataframes. 

# Then we can use the concat method again to combine all the dataframes. 

### Consider the following example.

## we are making a new dataframe
df1 = pd.DataFrame({'col1': ['col10', 'col11', 'col12', 'col13'],
                    'col2': ['col20', 'col21', 'col22', 'col23'],
                    'col3': ['col30', 'col31', 'col32', 'col33'],
                    'col4': ['col40', 'col41', 'col42', 'col43']},
                   index=[0, 1, 2, 3])
df1

col1   col2   col3   col4
0  col10  col20  col30  col40
1  col11  col21  col31  col41
2  col12  col22  col32  col42
3  col13  col23  col33  col43

In [0]:
# making another data frame
df4 = pd.DataFrame({'col2': ['col22', 'col23', 'col26', 'col27'],
                    'Col4': ['Col42', 'Col43', 'Col46', 'Col47'],
                    'col6': ['col62', 'col63', 'col66', 'col67']},
                   index=[2, 3, 6, 7])
print(df4)

    col2   Col4   col6
2  col22  Col42  col62
3  col23  Col43  col63
6  col26  Col46  col66
7  col27  Col47  col67


In [0]:
# [54]
pd.concat([df1,df4], axis=1)

col1   col2   col3   col4   col2   Col4   col6
0  col10  col20  col30  col40    NaN    NaN    NaN
1  col11  col21  col31  col41    NaN    NaN    NaN
2  col12  col22  col32  col42  col22  Col42  col62
3  col13  col23  col33  col43  col23  Col43  col63
6    NaN    NaN    NaN    NaN  col26  Col46  col66
7    NaN    NaN    NaN    NaN  col27  Col47  col67

In [0]:
print(df1,"\n")
print(df4)
# [55]
pd.concat([df1,df4], axis=0)

    col1   col2   col3   col4
0  col10  col20  col30  col40
1  col11  col21  col31  col41
2  col12  col22  col32  col42
3  col13  col23  col33  col43 

    col2   Col4   col6
2  col22  Col42  col62
3  col23  Col43  col63
6  col26  Col46  col66
7  col27  Col47  col67


Col4   col1   col2   col3   col4   col6
0    NaN  col10  col20  col30  col40    NaN
1    NaN  col11  col21  col31  col41    NaN
2    NaN  col12  col22  col32  col42    NaN
3    NaN  col13  col23  col33  col43    NaN
2  Col42    NaN  col22    NaN    NaN  col62
3  Col43    NaN  col23    NaN    NaN  col63
6  Col46    NaN  col26    NaN    NaN  col66
7  Col47    NaN  col27    NaN    NaN  col67

# Combining Datasets: Merge and Join

The pd.merge() function implements a number of types of joins: 
a> one-to-one join
b> many-to-one join, and 
c> many-to-many join. 

All three types of joins are accessed via an identical call to the pd.merge() interface; the type of join performed depends on the form of the input data.

One-to-one joins

One-to-one join, is similar to the column-wise concatenation.

In [0]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
    'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [0]:
# [57]
df3 = pd.merge(df1,df2)
df3

# The pd.merge() function recognizes that each DataFrame has an 
# “employee” column, and automatically joins using this column as a key.

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

Many-to-one joins

Many-to-one joins are joins in which one of the two key columns contains duplicate entries. 

For the many-to-one case, the resulting DataFrame will preserve those duplicate
entries as appropriate. Consider the following example of a many-to-one join:

In [0]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); 
# [58]
print(pd.merge(df3,df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


The resulting DataFrame has an additional column with the “supervisor” information, where the information is repeated in one or more locations as required by the inputs.

Many-to-many joins

Many-to-many joins are a bit confusing conceptually, but are nevertheless well
defined. If the key column in both the left and right array contains duplicates, then the result is a many-to-many merge.

In [0]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],
'skills': ['math', 'spreadsheets', 'coding', 'linux',
'spreadsheets', 'organization']})

print(df1,"\n"); print(df5,"\n"); 
print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization 

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


Note 1 : Specification of the Merge Key : 
We’ve already seen the default behavior of pd.merge(): it looks for one or more
matching column names between the two inputs, and uses this as the key. However, often the column names will not match so nicely.

Solution : Use on keyword
Most simply, you can explicitly specify the name of the key column using the on keyword, which takes a column name or a list of column names:

In [0]:
print(df1); print(df2);

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [0]:
print(df1); print(df2); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


The left_on and right_on keywords

At times you may wish to merge two datasets with different column names; for example, we may have a dataset in which the employee name is labeled as “name” rather than “employee”. In this case, we can use the left_on and right_on keywords to specify the two column names:

In [0]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})

print(df1,"\n"); print(df3,"\n");

print(pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000 

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


Inner and Outer Join

Upto now, we have merged two datasets using Inner join.

for example :

In [0]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
    'food': ['fish', 'beans', 'bread']},
    columns=['name', 'food'])

df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
    'drink': ['wine', 'beer']},
    columns=['name', 'drink'])

print(df6,"\n"); print(df7); 
pd.merge(df6, df7) #by default, this takes the inner join

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread 

     name drink
0    Mary  wine
1  Joseph  beer


name   food drink
0  Mary  bread  wine

In [0]:
pd.merge(df6, df7, how='inner')

Other options for the how keyword are 'outer', 'left', and 'right'. 

An outer join returns a join over the union of the input columns, and fills in all missing values with NAs.

In [0]:
print(df6);  print("--------------"); print(df7); 

pd.merge(df6, df7, how='outer')

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
--------------
     name drink
0    Mary  wine
1  Joseph  beer


name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

# Practice Problems

In [0]:
# Because Pandas is designed to work with NumPy, 
# any NumPy ufunc will work on Pandas Series and DataFrame objects
# all missing values are filled in with NaN by default:

# What is the o/p ?
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print(A);print("----------------------");print(B)

A + B

0    2
1    4
2    6
dtype: int64
----------------------
1    1
2    3
3    5
dtype: int64


0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [0]:
# add two series and fill missing value with 0, instead of NaN
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print(A);print("----------------------");print(B)

A.add(B, fill_value=0)

0    2
1    4
2    6
dtype: int64
----------------------
1    1
2    3
3    5
dtype: int64


0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

>> Detecting null values 
Pandas data structures have two useful methods for detecting null data: 
    isnull() and notnull(). 
Either one will return a Boolean mask over the data.

In [0]:
# What is the output ?
#None and nan both are considered as null by isnull()
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [0]:
# for the series 
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
#or data = pd.Series([1, np.nan, 2, None, 3], index=list(['a','b','c','d','e']))

print(data)
# [71]
data.fillna(method= 'ffill')

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [0]:
# specify a back-fill to propagate the next values backward:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

# GroupBy: Split, Apply, Combine

![Split Apply Combine Diagram](datasets_n_images/images/split_apply_combine.png "Split Apply Combine Image")

In [0]:
# an example of split - apply - combine 
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                    'data': [1,2,3,4,5,6]}, columns=['key', 'data'])

df

key  data
0   A     1
1   B     2
2   C     3
3   A     4
4   B     5
5   C     6

In [0]:
# [95]
df.groupby('key')

In [0]:
# [96]
df.groupby('key').sum()

data
key      
A       5
B       7
C       9

Aggregate, filter, transform, apply : more examples ....
---------------------------------------------------------
In particular, GroupBy objects have aggregate(), filter(), transform(), and apply() methods that efficiently implement a variety of useful operations before combining the grouped data.

In [0]:
rng = np.random.RandomState(0)

df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                    'data1': range(6),
                    'data2': rng.randint(0, 10, 6)},
                     columns = ['key', 'data1', 'data2'])

df

Aggregation 
-----------
We’re now familiar with GroupBy aggregations like sum(), median(),
and the like, but the aggregate() method allows for even more flexibility. 

It can take a string, a function, or a list thereof, and compute all the aggregates at once. 

Here is a quick example combining all these:

In [0]:
# [99]


Filtering. A filtering operation allows you to drop data based on the group properties.

For example, we might want to keep all groups in which the standard deviation is larger than some critical value:

In [0]:
def filter_func(x):
 return x['data2'].std() > 4

# prints the data frame
print(df); 
print("------------------------")

# prints the data frame grouped on key and std deviation per group
print(df.groupby('key').std());
print("------------------------")

# prints the data frame
print(df.groupby('key').filter(filter_func))

The apply() method. 
-------------------
The apply() method lets you apply an arbitrary function to the group results. 

The function should take a DataFrame, and return either a Pandas object 
(e.g., DataFrame, Series) or a scalar; the combine operation will be tailored to the type of output returned.

For example, here is an apply() that normalizes the first column by the sum of the second:

In [0]:
def norm_by_data2(x):
 # x is a DataFrame of group values
 x['data1'] /= x['data2'].sum()
 return x

print(df); 
print("----------------")
print(df.groupby('key').apply(norm_by_data2))

Note : apply() within a GroupBy is quite flexible: the only criterion is that the function takes a DataFrame and returns a Pandas object or scalar; what you do in the middle is up to you!

# Making Pivot Tables

In [0]:
# For the examples in this section, we’ll use the database of passengers 
# on the Titanic, available through the Seaborn library

import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.head()

This contains a wealth of information on each passenger of that ill-fated voyage, including gender, age, class, fare paid, and much more.
-----------------------------------------------------------------------------

To start learning more about this data, we might begin by grouping it according to gender, survival status, or some combination thereof. If you have read the previous section, you might be tempted to apply a GroupBy operation—for example, let’s look at survival rate by gender:

In [0]:
titanic.groupby('sex')['survived'].mean()

In [0]:
titanic.groupby('sex')[['survived']].mean()

This immediately gives us some insight: overall, three of every four females on board survived, while only one in five males survived!

This is useful, but we might like to go one step deeper and look at survival by both sex and, say, class. 

Using the vocabulary of GroupBy, we might proceed using something like this: we group by class and gender, select survival, apply a mean aggregate, combine
the resulting groups, and then unstack the hierarchical index to reveal the hidden multidimensionality. In code:

In [0]:
# Pivot Table Syntax
# Here is the equivalent to the preceding operation using 
# the pivot_table method of DataFrames:

titanic.pivot_table('survived', index='sex', columns='class')

# This is eminently more readable than the GroupBy approach, 
# and produces the same result.

This gives us a better idea of how both gender and class affected survival, but the code is starting to look a bit garbled. While each step of this pipeline makes sense in light of the tools we’ve previously discussed, the long string of code is not particularly easy to read or use. 

Pandas includes a convenience routine, pivot_table, which easily handles this type of multidimensional aggregation.

The full call signature of the pivot_table method of DataFrames is as follows:

DataFrame.pivot_table(data, values=None, index=None, columns=None,
aggfunc='mean', fill_value=None, margins=False,
dropna=True, margins_name='All')

For further reading on "Pandas Pivot Tables" see
https://pbpython.com/pandas-pivot-table-explained.html